### ISSUE TITLE
Create READMEs for each sub team's branch

### ISSUE THREAD

**Issue by ikale1234** [cse110-sp24-team24/cse110-sp24-team24#52]
Create a detailed readme for each branch's work progress, newly introduced functionality, how it works, anything else you find useful : 0

Plz check off the list when done:

- [x] Team 1 README     8 D
- [x] Team 2 README     0_0
- [x] Team 3 README     : P

**Comment by kieraliz** [comment]
All READMes are updated in ...
- team1-electron
- team2-tagsystem
- team3-alt-codeblocks/testing
